#
# Travis CI configuration
#
# Simply tests that Home Assistant configuration is valid.
#
# @link https://docs.travis-ci.com/user/tutorial/
# @link https://www.home-assistant.io/docs/ecosystem/backup/backup_github/#step-7-configuration-file-testing
#

# Select the base environment
language: python
python:
  - "3.7"

# Enable Travis caching of Python Packages (per branch)
cache: pip

# Prepare the CI environment to support Home Assistant
before_install:
  - mv secrets_travis.yaml secrets.yaml
  - touch home-assistant_v2.db
  - touch home-assistant.log
  - HA_VERSION=$(<.HA_VERSION)

# Install Home Assistant
install:
  - pip3 install homeassistant==${HA_VERSION}

# Test configuration files
script:
  - hass --script check_config --config . --files

notifications:
  webhooks:
    urls:
      - "UQ0DguzvCi9tTBjCe4R8HHngcdzIliMssSAPiXtuVYKbrTBWuBgQ86T3yJz5W4vjV1QNG0PxhjyUdcH+4Ta6X+hmId4Q+bXxKthyC7Ko/fvLlfFGZf/plhF6tMZtL1Zkt0LeZ8L+Fmgld//zrsJ+yzlFUn8KpZwDLQNYB97gjXFEgOsW94pwD8Xgo+sCnEt1ueyebF/1MvmQFFgLBIbrvsnI2nlh50dlb4OEz9VcJWXLaphxBuX/OzKhhk1LLe67/eGssMRGD6Y4VMh5Oc6Oitf8Juj4YOXXYRuupymEKIDdXZxpv3V+bOHMzUQYTDGkmnzMj4BeVPOrBgQ1bP3fd+scCkNCrW7ZRGvT9MV7BLJVQwTdAsGLMDFn3FkKFiF0hcFYI+TOvJ19yfryhmXgG73MTCJMzjd2SdUxerxbiiOPIOHbJ/OvbUIxkxIDB1HyLc0dBH31IlGsBw6txB1gvidSKhXrIEZ+rBtlaz7jLqphEmeUDJQLTgK4FUXdAosKxWIAYZNUuH+Cl5z2+SftV4dmmtv4P120VYQ904l4Jvleu4Q8F59IQ1DRjK+kaFlxzq7cHjbEUsqQfL0Nnoo7m+Q0NloRie71g6L0CUgWB8LPbQqfeWs9gmpzQmGf9WepSu7F6ckb9L4KBv3a7GvlXnHfCrh+hM3ZVRSY/SkZ/Ko=" 
    on_success: always
    on_failure: always
    on_start:   always