#
# Travis CI configuration
#
# Simply tests that Home Assistant configuration is valid.
#
# @link https://docs.travis-ci.com/user/tutorial/
# @link https://www.home-assistant.io/docs/ecosystem/backup/backup_github/#step-7-configuration-file-testing
#

# Select the base environment
language: python
python:
  - "3.7"

# Enable Travis caching of Python Packages (per branch)
cache: pip

# Prepare the CI environment to support Home Assistant
before_install:
  - mv secrets_travis.yaml secrets.yaml
  - touch home-assistant_v2.db
  - touch home-assistant.log
  - HA_VERSION=$(<.HA_VERSION)

# Install Home Assistant
install:
  - pip3 install homeassistant==${HA_VERSION}

# Test configuration files
script:
  - hass --script check_config --config . --files

notifications:
  webhooks:
    urls:
      secure: "NbE4fCL/zfa5DVV01E2c5A9gIDXp5tFnTjffIidN1QXgs7uKAscbqPUk9ubvnzOEz08twm9oADxZUTVfHg6KefWbET3hWEFYe/Q0/PRQL6BWJG3aH6MdILQUCPmAjh8miWVCBhnLsDF2MRrnUwYCS9dAy+uUwgqqiee2PNBk4/MXI6pdsTuW9RWt42Qz16/YNp1017SDfvP+cOW6zQZSIpN7UCztBXd3RSHR+I4J3X/ebD6v7pIX/XLHtX7GVuUGMQEI/N9lI9VNXXFLmuMN0brJeh0vcT2xge9045Eb91slIw369s55o9TMFeR+qkJwEB5ogXOdVfm1KFi6aQ/YQFSQi2PjSUekUT0P7FQhCKukrBSXiJJutd5O2WwHSRp2ipsN3aozNC1stC7GKm4Gj1CeoZXE0rzqT3cwK0T4drYl8Wz3kckZmz6uLoSo7uNKCkUWAA1YeUW7FHSC6W2GEuXc7UVO/GStHiBB6JOoqzdWCuORoDR7id4uv1tflo4n9piFCNvXSkz2aodE62zZZhW8S4r7x0Mu7MwTXvsjLOpB5dtuEw25Zv5PlwaU5aOO5PJ80s6XlLr8V617s8n3VbXxpTLSJJcp5GbjHyA1DCQuit+xZDkNuKw0ckaXQwnDonbVxwry7Xrky7F+sfg201Y+60xd8cxHy/fOxh0fw3g="
    on_success: always
    on_failure: always
    on_start:   always