#
# Travis CI configuration
#
# Simply tests that Home Assistant configuration is valid.
#
# @link https://docs.travis-ci.com/user/tutorial/
# @link https://www.home-assistant.io/docs/ecosystem/backup/backup_github/#step-7-configuration-file-testing
#

# Select the base environment
language: python
python:
  - "3.7"

# Enable Travis caching of Python Packages (per branch)
cache: pip

# Prepare the CI environment to support Home Assistant
before_install:
  - mv secrets_travis.yaml secrets.yaml
  - touch home-assistant_v2.db
  - touch home-assistant.log
  - HA_VERSION=$(<.HA_VERSION)

# Install Home Assistant
install:
  - pip3 install homeassistant==${HA_VERSION}

# Test configuration files
script:
  - hass --script check_config --config . --files

notifications:
  webhooks:
    urls:
      - "tGdzhIIMMmR/fxFPuXeYToWEMpFvq2T2RQ+1F6IWMfh/fD1GDjg0B8ieN2ro3u/uFtunsb6rCEZrZP66Gti2QdxyMnA1TKcuRJ+2KBYKx4XCAb9Vx9ek6kj1M1cKef2WmauNIIatyqH3/2FEfTxWeYPA5LuK+iGHHm0klyZL3o9n2GKzreJdLkVBdkCADsioB/93wM/d0ZeIOApLzIE0ydmwp2Wj5cpaI/Xb5I6m9W64CawepEnrT8E9GoOA+yZuTnF6IGs8Xuj6uhMftu6vLLK27pbvnqPWQBEcwcpUAeooxuKiG8+m0QJe6E716eqhSnHCxd8cRsSbMK9OSpmQlJlaS1cVw1gdyUToRaFXH9dpcEL8sSFzYcDDuSxqfqpYvUNIby7nV4W9RNF7a/ffZDWSqYHs7RqsQV4MZSvIPSJ8DyZgJ6BEXJSILFOvtGzMr1oa7ckIKgPpCKCNRiO+NoTQHpm2TOgeSsPKZDQyWsY5UMFlYX2MLSofKTwCAI6iPMwltCd3QMTiqq9ppQeqX4XjPUevT+CXRAb7GnxSYkfXo0I0FCOPrEHY0GkrVQ0dwckBInn/GqqiFJCwNq2S99aI6nMN+E8nUb1noJ6TfuAJ3CrjSTpfiCTQQ7Z3pjprFhvNUTWNYkc7oj09TGxJ8/aoWoQl6tEKSyo+wRzNFP0="
    on_success: always
    on_failure: always
    on_start:   always