- id: homeassistant_start
  alias: homeassistant_start
  trigger:
  - platform: homeassistant
    event: start
  action:
  - service: shell_command.update_ci_cur_ver
- id: '1624214565059'
  alias: Work laptop on
  description: Receive webhook from work laptop every 30 minutes
  trigger:
  - platform: webhook
    webhook_id: work_laptop_on
  condition: []
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.work_laptop_online
  mode: single
