# Main Doors
- platform: mqtt
  name: "Front Door Opened"
  state_topic: "hasshub/binary_sensor/front_door_opened/state"
  payload_on: "on"
  payload_off: "off"
  qos: 0
  device_class: opening

- platform: mqtt
  name: "Back Door Opened"
  state_topic: "hasshub/binary_sensor/back_door_opened/state"
  payload_on: "on"
  payload_off: "off"
  qos: 0
  device_class: opening

- platform: mqtt
  name: "Garage Entry Door Opened"
  state_topic: "hasshub/binary_sensor/garage_entry_door_opened/state"
  payload_on: "on"
  payload_off: "off"
  qos: 0
  device_class: opening

# Basement
- platform: mqtt
  name: "Basement Door Opened"
  state_topic: "hasshub/binary_sensor/basement_door_opened/state"
  payload_on: "on"
  payload_off: "off"
  qos: 0
  device_class: opening

- platform: mqtt
  name: "Basement Stairs Motion"
  state_topic: "hasshub/binary_sensor/basement_stairs_motion/state"
  payload_on: "on"
  payload_off: "off"
  qos: 0
  device_class: motion

- platform: mqtt
  name: "Basement Media Room Motion"
  state_topic: "hasshub/binary_sensor/basement_media_room_motion/state"
  payload_on: "on"
  payload_off: "off"
  qos: 0
  device_class: motion

- platform: mqtt
  name: "Deep Freeze Opened"
  state_topic: "hasshub/binary_sensor/deep_freeze_opened/state"
  payload_on: "on"
  payload_off: "off"
  qos: 0
  device_class: opening

# Windows
- platform: mqtt
  name: "Right Basement Window Opened"
  state_topic: "hasshub/binary_sensor/right_basement_window_opened/state"
  payload_on: "on"
  payload_off: "off"
  qos: 0
  device_class: opening

- platform: mqtt
  name: "Left Basement Window Opened"
  state_topic: "hasshub/binary_sensor/left_basement_window_opened/state"
  payload_on: "on"
  payload_off: "off"
  qos: 0
  device_class: opening

- platform: mqtt
  name: "Left Dining Window Opened"
  state_topic: "hasshub/binary_sensor/left_dining_window_opened/state"
  payload_on: "on"
  payload_off: "off"
  qos: 0
  device_class: opening

- platform: mqtt
  name: "Middle Dining Window Opened"
  state_topic: "hasshub/binary_sensor/middle_dining_window_opened/state"
  payload_on: "on"
  payload_off: "off"
  qos: 0
  device_class: opening

- platform: mqtt
  name: "Right Dining Window Opened"
  state_topic: "hasshub/binary_sensor/right_dining_window_opened/state"
  payload_on: "on"
  payload_off: "off"
  qos: 0
  device_class: opening

- platform: mqtt
  name: "Stair Window Opened"
  state_topic: "hasshub/binary_sensor/stair_window_opened/state"
  payload_on: "on"
  payload_off: "off"
  qos: 0
  device_class: opening


- platform: template
  sensors:
    living_room_ec:
      value_template: "{{ states('sensor.living_room_ec_current_consumption')|float > 10 }}"
      friendly_name: 'Living Room TV'
      device_class: power

    brooks_snoo_status:
      friendly_name: 'Brooks Snoo Status'
      value_template: "{{ states('sensor.brooks_snoo_outlet_power_sensor')|float > 4 }}"
      device_class: power

    brooks_space_heater_status:
      friendly_name: 'Brooks Space Heater Status'
      value_template: "{{ states('sensor.brooks_space_heater_power')|float > 10 }}"
      device_class: power

    bottle_warmer_status:
      friendly_name: 'Bottle Warmer Status'
      value_template: "{{ states('sensor.bottle_warmer_stats_5min')|float > 10 }}"
      device_class: power

- platform: mqtt
  name: Garage Main Door Open
  state_topic: "garage/bigdoor/2/cmnd/POWER2"
  payload_on: "OFF"
  payload_off: "ON"

- platform: mqtt
  name: Garage Side Door Open
  state_topic: "garage/sidedoor/2/cmnd/POWER2"
  payload_on: "OFF"
  payload_off: "ON"
