title: Home
resources:
  - url: /local/alarm_control_panel-card.js?v=1
    type: js
views:
  - title: Downstairs
    cards:
      - type: entities
        id: garage_entry_card
        title: Garage Entry
        show_header_toggle: false
        entities:
          - switch.garage_entry
          - lock.garage_entry_door
      - type: entities
        id: kitchen_card
        title: Kitchen
        show_header_toggle: false
        entities:
          - lock.back_door
          - switch.breakfast_table_light
          - light.deck_light
          - light.kitchen_cabinet
          - switch.kitchen_bar
